### ISSUE TITLE
No response while setting annotation properties

### ISSUE THREAD

**Issue by DanAmador** [BeamNG/impactgen#1]
Good day, 

I'm trying to run the script and generate some test data, but it gets stuck [while waiting for a response](https://github.com/BeamNG/impactgen/blob/0ea1b59c6d941fd0557f2f4b05694b85c08188d6/python/src/impactgen/impactgen.py#L318).

I don't get an error message or anything, the Beamng.tech build also loads without a problem.

![image](https://user-images.githubusercontent.com/7833567/115160281-bf9a5300-a097-11eb-9403-fd3a590a1fc1.png)

Do you have an idea what could be causing this?

**Comment by Palculator** [comment]
Seeing as it's stuck on the very first call to an ImpactGen-specific handler, is the ImpactGen Lua extension maybe not set up properly? It needs to be copied over as described in the README: https://github.com/BeamNG/impactgen#lua

There should be a file `lua/ge/extensions/impactgen/crashOutput.lua`. You can try manually starting the game and running `extensions.load('impactgen/crashOutput')` to see if the extension is available.

**Comment by DanAmador** [comment]
Thank you, 

it got solved by adding the file to my user path.
