### ISSUE TITLE
Missing 'zipper' module in lua module

### ISSUE THREAD

**Issue by Fable67** [BeamNG/impactgen#2]
In the lua library you use a supposed module called 'zipper' to pack files into a zip. However, this module is not available.

**Comment by aivora-beamng** [comment]
Hi, this tool was developed for BeamNG.tech 0.21 and BeamNGpy 1.19.1 and will not work with other versions (in BeamNG.tech 0.21, the `zipper` module is available). I will add the information about that to the README file.

Thanks for your interest in the project, we are also working on making the tool work on the latest version of BeamNG.tech.

**Comment by aivora-beamng** [comment]
Hi, `impactgen` was updated for the latest version of BeamNG.tech (0.30) and BeamNGpy (1.27). You can try using this release :)
